server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: IMHERE-API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: [ GET, POST, PUT, DELETE, OPTIONS ]
                allowedHeaders: "*"
          routes:
            - id: notification               # ??? id
              uri: lb://IMHERE-NOTIFICATION-SERVICE   # ???? ??? ??
              predicates:                   # ??? ??
                - Path=/first-service/**
